name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: centos-s-1vcpu-1gb-fra1-01
    steps:
      - name: Deploy Oleh app
        uses: actions/checkout@v2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            mkdir test 
            cd test 
            git clone git@github.com:olehpitsun/ci_cd.git
            echo 'Deployment successful to digital ocean' 
